### ISSUE TITLE
Schedule's Time Set Not Working Properly

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kapua#1071]
When setting schedule for a certain job, when user picks start/end hour, drop down menu does not work properly (look at screenshot bellow). 

1. Login as kapua-sys
2. Go to Jobs, create a job (e.g. job1)
3. Go to job1 Schedule and enter schedule name, start and end date. 
4. Enter start and end time.
5. Try to change start and/or end time. 
**At this point Kapua shows only the time previously chosen. It has to be manually deleted in order to get all the other options (look at the screenshot bellow).**

<img width="1435" alt="screen shot 2017-11-27 at 11 14 12" src="https://user-images.githubusercontent.com/15121999/33261700-009f6278-d364-11e7-8e7b-6d06e81f64ea.png">

Browsers used:
- Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit))
- Safari (Version 11.0.1 (13604.3.5))
- Mozilla Firefox (57.0 (64-bit))
- Opera (Version 49.0.2725.39)

**Comment by Coduz** [comment]
This is because the dropdown is filtered with the value currently set. 
There is an option for showing all values, regardless the value chosen.

**Comment by Coduz** [comment]
This view has changed by now. This issue is fixed

**Comment by LeoNerdoG** [comment]
@Coduz This issue still persists in _**Ends On:**_ time part field (if user for example selects "00:00" and the wants to change to something else, only this option is in dropdown menu). However if user sets a end time, after that click anywhere else and then again on _**Ends On:**_ time part field the dropdown menu opens normally. 
The **Starts On:** time part of the field works even stranger. If user first selects a time (e.g. "00:15), after another click the "00:00" option is shown (nothing else) and after another click dropdown menu works normally. 

Regards, 
Leonardo
