### ISSUE TITLE
Console corrupts device configuration for devices with multiple configuration properties

### ISSUE THREAD

**Issue by gitsaycat** [eclipse/kapua#2300]
**Describe the bug**
The Kapua Console Device Configuration tab sends a bad modification update request XML when updating services configurations with more than 1 property through MQTT Request Response channel. This corrupts configuration values on the device permanently and prevents any further configuration operations

**To Reproduce**
1. Use the configuration file in the attached zip file for a configurable node
[kapua-bug.zip](https://github.com/eclipse/kapua/files/2748344/kapua-bug.zip)

2. Load the configuration for the node in the Configuration tab
3. Change the last item from 'lib' to 'TEST'
4. The console fails to correctly load the configuration after this as the backend configuration values are completely messed up 

**Expected behavior**
The system should successfully load the updated values for the property

**Screenshots**
See screenshot in attached zip file

**Version of Kapua**
1.0.0.M7

**Type of deployment**
[ ] Docker

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)

**Comment by lorthirk** [comment]
Hi,

It would be interesting if you could test a newer version of Kapua. For instance, #2093 has been fixed in 1.0.1 and it could also fix your issue.

**Comment by gitsaycat** [comment]
Ok - tested on 1.0.3
In M7 the modification request was actually always missing 1 property and in 1.0.3 all properties are being sent across.
Wonderful results - Thanks for the tip, hadn't noticed the upgrade was available.

**Comment by gitsaycat** [comment]
Note that there is a minor issue still.
The update succeeds and the UI is correctly refreshed going forward but it does throw up a quiet notification about the device being offline. 
Actually looking into the logs, it seems some code in the console chokes on the response XML after the update is complete and its refreshing itself. Doesn t seem to affect anything but could be something to do with BOM on the XML being sent back - will check.

> Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.eclipse.persistence.internal.oxm.record.XMLReader.parse(XMLReader.java:243)
        at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:1016)
        ... 71 common frames omitted

**Comment by Coduz** [comment]
Hi @gitsaycat ,

any update on the last issue that you found? 

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hi Alberto
![error](https://user-images.githubusercontent.com/14805543/53417372-6a5edb80-3a10-11e9-87c9-10ac668f86ed.jpg)

The issue still exists. As I mentioned (see attached screenshot), functionally this is working currently so its not critical - but the exception (see stacktrace in prior post) is being thrown and the there is the error message on the front end .
Thanks!

**Comment by Coduz** [comment]
Hi @gitsaycat ,

What error is shown in the Web Console log? 

Regards, 

_Alberto_

**Comment by gitsaycat** [comment]
Hi Alberto – in the browser there is an error notification that says the device is offline. I have attached screen shot to the original bug report.
The backend error seems to show that the server failed to parse the XML payload.
Regards,
Saycat

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Coduz** [comment]
Hi @gitsaycat ,

I was expecting that. 

This error comes from the fact that the configuration sent from the device is not properly formatted. The error shown in console is wrong. The actual error is the one on the Web Console logs.

Your registered device seems not being Kura-based, right? 

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Any news on this?

Regards,

_Alberto_

**Comment by Coduz** [comment]
Hi @gitsaycat ,

Closing this.
Feel free to reopen the issue if you need more help.

Regards, 

_Alberto_
